### ISSUE TITLE
CI: Add `concurrency` configuration

### ISSUE THREAD

**Issue by sebastianst** [perun-network/erdstall-ts-sdk#123]
Use the [`concurrency`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency) feature of Github Workflows to enhance the CI for pull requests. Per pull-request, it should cancel any ongoing or pending runs, if newer code is pushed. This might just be achieved by adding the following
```yaml
concurrency: 
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true
```
But this has to be checked.
